version: "2.4"

services:
  forecast-research:
    image: forecast-research
    build: .
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - TF_CPP_MIN_LOG_LEVEL=2
    runtime: $DOCKER_RUNTIME
    volumes:
      - .:/workspace
    entrypoint: ["jupyter","lab","--ip=0.0.0.0","--port=8888","--allow-root","--NotebookApp.token=","--NotebookApp.password="]
    ports:
      - "8888:8888"
